sonar.projectKey=secure-flask-app
sonar.projectName=secure-flask-app
sonar.sources=.
sonar.exclusions=venv/**,audit-env/**,__pycache__/**,.git/**
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.host.url=http://34.226.213.75:9000
